on: push
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - run: node --version
      - run: npm --version

      - name: Setup Ruby
        uses: ruby/setup-ruby@1.9.3
        with:
          ruby-version: 2.7
